# This workflow will do a clean install of node dependencies, build the source code, and deploy to GitHub Pages
name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - run: npm ci
    - run: npm run build --if-present
      
    - name: Deploy
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
        BASE_BRANCH: develop
